### ISSUE TITLE
qpointer_adapter class name typo

### ISSUE THREAD

**Issue by fdarling** [palacaze/sigslot#33]
I noticed typos in the following file:

https://github.com/palacaze/sigslot/blob/f8c275df5037bfb6d57c74168634b65fdbfb44f3/include/sigslot/adapter/qt.hpp#L18

 `qpointer_adater` should be `qpointer_adapter` (it's missing a "p"). It should be an easy fix!

By the way, I haven't yet used the library, but I am impressed with what I've seen so far! I've used a similar library from years ago, and was recently looking for something I could include as a git submodule.

**Comment by palacaze** [comment]
Fixed, thanks.
