### ISSUE TITLE
Release a new version with the latest bugfixes

### ISSUE THREAD

**Issue by vbieleny** [palacaze/sigslot#37]
Hello,

first of all, thank you for this library. We have decided to use it via a [Conan package manager](https://github.com/conan-io/conan) ([here](https://conan.io/center/sigslot)) and we've encountered the bug #31, which was already fixed in master but is not in the latest release.

Would it be possible to release a new version of this library?

Thank you.

**Comment by palacaze** [comment]
Thanks for the reminder, I just released v1.2.2.
