### ISSUE TITLE
use with microsoft/proxy with args

### ISSUE THREAD

**Issue by lty123456** [palacaze/sigslot#44]
I want use sigslot with [microsoft/proxy](https://github.com/microsoft/proxy),but connect only work when function without arg,for example:

    pro::proxy<FDrawable> f = MakeDrawableFromCommand();

    sigslot::signal<> sigVoid;
    sigslot::signal<float> sigFloat;

    sigVoid.connect(&pro::proxy<FDrawable>::invoke<Draw>, &f);                    //work
    sigFloat.connect(&pro::proxy<FDrawable>::invoke<DrawFloat>, &f);           //can not compiled

Full code: https://godbolt.org/z/fbvbcdjqo
    
is it possible make arg funcion work and how to do it?

**Comment by palacaze** [comment]
Hi,
Would that be acceptable to you: https://godbolt.org/z/Mx695aPs4 ?

**Comment by lty123456** [comment]
thanks for the answer and efficient
