### ISSUE TITLE
Signal Chaining

### ISSUE THREAD

**Issue by DxUr** [palacaze/sigslot#46]
`sigslot::connect` does not exist.
`sig2.connect(sig1)` gives compile error.

**Comment by palacaze** [comment]
Hi,

There is a freestanding [sigslot::connect](https://github.com/palacaze/sigslot/blob/dbbe4a1cf6528188443983cde6fba0bf38e7aa49/include/sigslot/signal.hpp#L1650) function that takes two signals.

**Comment by DxUr** [comment]
@palacaze The latest released version v1.2.2 don't contains that functionality I checked the header file. I'm using conan for instance do don't forget update it as well.

**Comment by RudyB** [comment]
@palacaze  This function also does not appear with vcpkg and sigslot 1.2.2
